export const codes = {
  AUD: { text: 'australia', char: '1 $' },
  AZN: { text: 'azerbaijan', char: '1 ₼' },
  GBP: { text: 'united-kingdom', char: '1 £' },
  AMD: { text: 'armenia', char: '100 ֏' },
  BYN: { text: 'belarus', char: '1 BYN' },
  BGN: { text: 'bulgaria', char: '1 Лв' },
  BRL: { text: 'brazil', char: '1 R$' },
  HUF: { text: 'hungary', char: '100 Ft' },
  HKD: { text: 'hong-kong', char: '1 HK$' },
  DKK: { text: 'denmark', char: '1 Kr' },
  USD: { text: 'united-states-of-america', char: '1 $' },
  EUR: { text: 'european-union', char: '1 €' },
  INR: { text: 'india', char: '100 Rs' },
  KZT: { text: 'kazakhstan', char: '100 ₸' },
  CAD: { text: 'canada', char: '1 C$' },
  KGS: { text: 'kyrgyzstan', char: '100 KGS' },
  CNY: { text: 'china', char: '1 ¥' },
  MDL: { text: 'moldova', char: '10 L' },
  NOK: { text: 'norway', char: '10 kr' },
  PLN: { text: 'poland', char: '1 zł' },
  RON: { text: 'romania', char: '1 lei' },
  SGD: { text: 'singapore', char: '1 S$' },
  TJS: { text: 'tajikistan', char: '10 SM' },
  TRY: { text: 'turkey', char: '10 ₺' },
  TMT: { text: 'turkmenistan', char: '1 T' },
  UZS: { text: 'uzbekistn', char: "10000 so'm" },
  UAH: { text: 'ukraine', char: '1 ₴' },
  CZK: { text: 'czech-republic', char: '10 Kč' },
  SEK: { text: 'sweden', char: '10 kr' },
  CHF: { text: 'switzerland', char: '1 CHf' },
  ZAR: { text: 'south-africa', char: '10 R' },
  KRW: { text: 'south-korea', char: '100 ₩' },
  JPY: { text: 'japan', char: '100 ¥' },
  XDR: { text: '', char: '' },
}
