export const codes = {
  AUD: { text: 'australia', char: '1 $', curr: 'Австралийский доллар' },
  AZN: { text: 'azerbaijan', char: '1 ₼', curr: 'Азербайджанский манат' },
  GBP: {
    text: 'united-kingdom',
    char: '1 £',
    curr: 'Фунт стерлингов Соединенного Королевства',
  },
  AMD: { text: 'armenia', char: '100 ֏', curr: 'Армянский драм' },
  BYN: { text: 'belarus', char: '1 BYN', curr: 'Белорусский рубль' },
  BGN: { text: 'bulgaria', char: '1 Лв', curr: 'Болгарский лев' },
  BRL: { text: 'brazil', char: '1 R$', curr: 'Бразильский реал' },
  HUF: { text: 'hungary', char: '100 Ft', curr: 'Венгерский форинт' },
  HKD: { text: 'hong-kong', char: '1 HK$', curr: 'Гонконгский доллар' },
  DKK: { text: 'denmark', char: '1 Kr', curr: 'Датская крона' },
  USD: { text: 'united-states-of-america', char: '1 $', curr: 'Доллар США' },
  EUR: { text: 'european-union', char: '1 €', curr: 'Евро' },
  INR: { text: 'india', char: '100 Rs', curr: 'Индийская рупия' },
  KZT: { text: 'kazakhstan', char: '100 ₸', curr: 'Казахстанский тенге' },
  CAD: { text: 'canada', char: '1 C$', curr: 'Канадский доллар' },
  KGS: { text: 'kyrgyzstan', char: '100 KGS', curr: 'Киргизский сом' },
  CNY: { text: 'china', char: '1 ¥', curr: 'Китайский юань' },
  MDL: { text: 'moldova', char: '10 L', curr: 'Молдавский лей' },
  NOK: { text: 'norway', char: '10 kr', curr: 'Норвежская крона' },
  PLN: { text: 'poland', char: '1 zł', curr: 'Польский злотый' },
  RON: { text: 'romania', char: '1 lei', curr: 'Румынский лей' },
  SGD: { text: 'singapore', char: '1 S$', curr: 'Сингапурский доллар' },
  TJS: { text: 'tajikistan', char: '10 SM', curr: 'Таджикский сомони' },
  TRY: { text: 'turkey', char: '10 ₺', curr: 'Турецкая лира' },
  TMT: { text: 'turkmenistan', char: '1 T', curr: 'Новый туркменский манат' },
  UZS: { text: 'uzbekistn', char: "10000 so'm", curr: 'Узбекский сом' },
  UAH: { text: 'ukraine', char: '1 ₴', curr: 'Украинская гривна' },
  CZK: { text: 'czech-republic', char: '10 Kč', curr: 'Чешская крона' },
  SEK: { text: 'sweden', char: '10 kr', curr: 'Шведская крона' },
  CHF: { text: 'switzerland', char: '1 CHf', curr: 'Швейцарский франк' },
  ZAR: { text: 'south-africa', char: '10 R', curr: 'Южноафриканский рэнд' },
  KRW: { text: 'south-korea', char: '100 ₩', curr: 'Вон Республики Корея' },
  JPY: { text: 'japan', char: '100 ¥', curr: 'Японская иена' },
  XDR: { text: '', char: '', curr: '' },
}
