export const codes = {
  AUD: { text: 'australia', char: '1$' },
  AZN: { text: 'azerbaijan', char: '1₼' },
  GBP: { text: 'united-kingdom', char: '1£' },
  AMD: { text: 'armenia', char: '100֏' },
  BYN: { text: 'belarus', char: '1BYN' },
  BGN: { text: 'bulgaria', char: '1Лв' },
  BRL: { text: 'brazil', char: '1R$' },
  HUF: { text: 'hungary', char: '100Ft' },
  HKD: { text: 'hong-kong', char: '1HK$' },
  DKK: { text: 'denmark', char: '1Kr' },
  USD: { text: 'united-states-of-america', char: '1$' },
  EUR: { text: 'european-union', char: '1€' },
  INR: { text: 'india', char: '100 &#x20B9' },
  KZT: { text: 'kazakhstan', char: '100₸' },
  CAD: { text: 'canada', char: '1C$' },
  KGS: { text: 'kyrgyzstan', char: '100KGS' },
  CNY: { text: 'china', char: '1¥' },
  MDL: { text: 'moldova', char: '10L' },
  NOK: { text: 'norway', char: '10kr' },
  PLN: { text: 'poland', char: '1zł' },
  RON: { text: 'romania', char: '1lei' },
  SGD: { text: 'singapore', char: '1S$' },
  TJS: { text: 'tajikistan', char: '10SM' },
  TRY: { text: 'turkey', char: '10₺' },
  TMT: { text: 'turkmenistan', char: '1T' },
  UZS: { text: 'uzbekistn', char: "10000so'm" },
  UAH: { text: 'ukraine', char: '1₴' },
  CZK: { text: 'czech-republic', char: '10Kč' },
  SEK: { text: 'sweden', char: '10kr' },
  CHF: { text: 'switzerland', char: '1CHf' },
  ZAR: { text: 'south-africa', char: '10R' },
  KRW: { text: 'south-korea', char: '100₩' },
  JPY: { text: 'japan', char: '100¥' },
  XDR: { text: '', char: '' },
}
